### ISSUE TITLE
Error command - Install the PHP graphics drawing library

### ISSUE THREAD

**Issue by adrianogarru** [awsdocs/amazon-ec2-user-guide#102]
Hi There,

This is Adriano and I am using the AWS for an educational purpose and I found a probable mismatch on the tutorial: 

Tutorial: Hosting a WordPress Blog with Amazon Linux 
- Topic: install the PHP graphics drawing library
- Command: _sudo yum install php72-gd_
This command triggered an error message: **No package php72-gd available.
Error: Nothing to do**

It looks like library has not been found.

**What I did:**

1)Run command: _rpm -qa | grep gd_
- Package looks like installed: **php-gd-7.2.27-1.amzn2.x86_64**

**What I suggest:**

- Explain in the guide to check if the library has been installed previously with the command: rpm -qa | grep gd
- Change the command in the tutorial to the correct one: _sudo yum install php-gd-7.2.27_ (this one seems to be recognized by the shell) in order to install it if not present in the system.

Please be informed on the below:

The previous tutorial followed [Install a LAMP Web Server on Amazon Linux 2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-lamp-amazon-linux-2.html)

Istance used:

NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"

Thanks for your time.
Regards,
Adriano

**Comment by julieso** [comment]
Thanks for pointing this out. My apologies for the delayed response.

I've done some testing and updated the documentation. There are now separate sections "To install the PHP graphics drawing library on Amazon Linux 2" and "To install the PHP graphics drawing library on the Amazon Linux AMI". You can see the HTML updates here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/hosting-wordpress.html. I'll update the markdown later this week.
