### ISSUE TITLE
(Optional) Install phpMyAdmin - Step 6 fix due to phpMyAdmin upgrade

### ISSUE THREAD

**Issue by stringsz** [awsdocs/amazon-ec2-user-guide#11]
In step 5 the command downloads the latest version of of phpMyAdmin (phpMyAdmin-4.8.0)  hence step 6 in this guide won't work.
Please update the guide to address the issue.

FIX - STEP 6
========
[ec2-user html]$ tar -xvzf phpMyAdmin-latest-all-languages.tar.gz
[ec2-user html]$ mv phpMyAdmin-4.8.0-all-languages phpMyAdmin

**Comment by julieso** [comment]
Thanks for pointing this out. I've updated the tutorial to make it version-neutral: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/install-LAMP.html.
