### ISSUE TITLE
Symmetrical bandwidth?

### ISSUE THREAD

**Issue by maxblaze** [awsdocs/amazon-ec2-user-guide#115]
The bandwidth limits listed here are useful, but it is not clear whether this is total available bandwidth (in + out) or symmetrical bandwidth, where the maximum is available to both in and out simultaneously. From my experience, it is the later, but it would be great for this to be officially spelled out in the docs.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-optimized.html

**Comment by julieso** [comment]
Hello. I see that you received an answer from support through another avenue. To summarize here, EBS is designed to achieve the documented performance regardless of the mix of read and write.
