### ISSUE TITLE
delete / disable ENA on linux

### ISSUE THREAD

**Issue by azfarhashmi** [awsdocs/amazon-ec2-user-guide#126]
What's the procedure to delete / disable ENA on Debian setup via DKMS?

**Comment by mariflax** [comment]
Hi. Have you tried the command pasted below, which is specified here? https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/troubleshooting-ena.html#ena-connectivity-issues

$ aws ec2 modify-instance-attribute --instance-id instance_id --no-ena-support
