### ISSUE TITLE
Hostname/nickname for root

### ISSUE THREAD

**Issue by matccent** [awsdocs/amazon-ec2-user-guide#129]
Hi, I'm following instructions from section **Changing the shell prompt without affecting the hostname** from https://github.com/awsdocs/amazon-ec2-user-guide/blob/master/doc_source/set-hostname.md

and I've set NICKNAME to MyServer

but when I switch to root user, then I can't see my nickname/hostname

```
[ec2-user@MyServer /]$ sudo su
[root@ /]#
[root@ /]# echo $PS1
[\u@ \W]\$
```

Apart from root user, it works fine.

**Comment by lkdavies** [comment]
Thank you for your request. A member of the team will be working on it and will provide updates here about progress.

**Comment by lkdavies** [comment]
Hello, thanks for reaching out to us regarding our documentation. 

The documentation demonstrates how to set the NICKNAME variable for the user ec2-user.  

I tested this procedure and found that if you sign in as the root user and then set the NICKNAME variable, the NICKNAME you choose is applied to the root user and ec2-user. 

I hope this information helps!
