### ISSUE TITLE
verify-pkcs7.md "Other AWS Regions" and GovCloud certificates are the same

### ISSUE THREAD

**Issue by cppopp-aws** [awsdocs/amazon-ec2-user-guide#172]
In Step 4, the docs say "The following AWS public certificate is for all AWS Regions, except Hong Kong, Bahrain, China, and GovCloud\." However, the certificate for GovCloud region is now the same as the one in this tab. Should the tab and call out for GovCloud be removed if the region now uses the same certificate?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
