### ISSUE TITLE
Update Documentation to include new or defunct features for Amazon Linux 2

### ISSUE THREAD

**Issue by mojoa** [awsdocs/amazon-ec2-user-guide#178]
People use documentation to discover the functionality of AWS products they are interested in. It is crucial this documentation reflect the true state of the features so that people do not waste time or become disappointed in the AWS product under review. 

Please consider updating the documentation to reflect a problem with AL2 ( Amazon Linux 2 ) where the seed.iso method for updating network setting upon boot does not work for all recent versions of the image using vmware virtualization.

**AWS Documentation**
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-2-virtual-machine.html

**Supporting:**

**Forum link https://forums.aws.amazon.com/thread.jspa?messageID=971373&#971373**

It appears as though this is method is broken and has been for some time.

This needs to be highlighted in the documentation, rather than wasting peoples time.

From the forum:

>    This is sadly still broken with the latest 2.0.20210126.0 release.
>  The documentation in the README.cloud-init is broken, as is the document here:
>    https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-2-virtual-machine.html
> The linked reply with a diff to fix cloud-init does look like it would work, but there's no way to patch this at boot time that I can >see. I'm really stuck trying to figure out how to work around this, and I'm still stuck loading a two year old image and then >upgrading it. Really frustrating - I've tried all sorts of yaml config variants for the seed.iso with no luck. 

**Forum link showing heath@aws seems to acknowledge the problem but I am not seeing any final resolution and it does not work in latest AL2 image.**

https://forums.aws.amazon.com/thread.jspa?messageID=971374&#971374

**Additional alternatives:**

https://github.com/awsdocs/amazon-ec2-user-guide/issues/123

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
