### ISSUE TITLE
EC2 Pricing Chart Display Issue

### ISSUE THREAD

**Issue by TNonet** [awsdocs/amazon-ec2-user-guide#179]
Hi, I don't think this is the correct area to raise this issue, but I am unaware of the correct area. 

If anyone knows, please direct me and I will close this issue.

I was looking through the [AWS EC2 Pricing charts](https://aws.amazon.com/ec2/pricing/on-demand/) and found that the sorting functionality works roughly as expected except for the "Memory" column which sorts lexicographically instead of by amount of memory.

This isn't a huge issue, but I have to imagine it could fool someone quickly searching for the largest and smallest memory instances.

**Comment by mariflax** [comment]
Hi. Good catch! Thanks for taking the time to let us know.

This area is for feedback about the EC2 docs, so I'll close this issue. But I'll definitely pass on your feedback to the correct team.
 
Thanks,
Marilyn Flax
AWS Documentation
