### ISSUE TITLE
Elastic Network Interfaces | Public Ip address vs Elastic Ip address

### ISSUE THREAD

**Issue by Dheerajmentor** [awsdocs/amazon-ec2-user-guide#18]
Hi Team, 

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html

above page has defined network interface attributes, but below points are not clear 

One Elastic IP address (IPv4) per private IPv4 address
One public IPv4 address

Elastic IP address it self means public ip address, so why it means by one Elastic IP address per IP4 address and One public ip address 

How many public ip address are possible ?

thank you 
dheeraj Kumar

**Comment by landermkerbey** [comment]
Dheeraj,

Note that the item above Elastic IP per private IP says "One or more secondary private IPv4 addresses from the IPv4 address range of your VPC."

So, it's possible to have additional private IP addresses, to which one Elastic IP is assigned. The 'One public IPv4' appears to refer to static IP for that interface, as opposed to Elastic IP which can be associated with different instances/interfaces as need be.

**Comment by katerini** [comment]
Closing this issue, but please do open a new issue if there any further issues.
