### ISSUE TITLE
ssh into Amzon Linux2 as a VM on-premise

### ISSUE THREAD

**Issue by saurabhkumar** [awsdocs/amazon-ec2-user-guide#188]
I followed all the instructions in the article [Run Amazon Linux 2 as a virtual machine on premises](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-2-virtual-machine.html).
I am using Oracle VirtualBox on Windows10. The port forwarding for **Port 22** is enabled for the VM.
I also modified **/etc/ssh/sshd_config** to change **PasswordAuthentication** to **yes** and did `sudo service sshd restart` .
I am able to login into the VM using the default EC2-user.
But I am not able to ssh into the VM.
What else am I missing? Is is mandatory to generate keys for accessing the instance using ssh? How do I generate the keys for the default ec-2 user in this case?

**Comment by cyc123456789** [comment]
It seems like you have to replace password when you edit `user-data`.

```
#cloud-config
#vim:syntax=yaml
users:
# A user by the name `ec2-user` is created in the image by default.
  - default
chpasswd:
  list: |
    ec2-user:plain_text_password
# In the above line, do not add any spaces after 'ec2-user:'.
```
Replace `plain_text_password` with a password of your choice for the default `ec2-user` user account.

**Comment by jmjesse** [comment]
You can review the [readme file](https://cdn.amazonlinux.com/os-images/2.0.20190612/README.cloud-init) for the seed.iso which has the syntax for SSH key generation, creating alternate users, and providing a password. You can specify your own keys, or have them generate for you. The [cloud-init module for SSH](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#ssh) has more information.

These snippets from the cloudinit documentation should address the questions posed:
> Authorized keys are a list of public SSH keys that are allowed to connect to a user account on a system. They are stored in .ssh/authorized_keys in that account’s home directory. Authorized keys for the default user defined in users can be specified using ssh_authorized_keys. Keys should be specified as a list of public keys.
...
Host keys can be added using the ssh_keys configuration key. The argument to this config key should be a dictionary entries for the public and private keys of each desired key type.
...
If no host keys are specified using ssh_keys, then keys will be generated using ssh-keygen. By default one public/private pair of each supported host key type will be generated.
