### ISSUE TITLE
Using ENI Update with Prefixes

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/amazon-ec2-user-guide#189]
https://github.com/awsdocs/amazon-ec2-user-guide/blob/master/doc_source/using-eni.md

With the recent release of the ability to assign prefixes to network interfaces during creation, should this be updated to reflect that change?

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/work-with-prefixes.html

**Comment by mariflax** [comment]
Yes! Thank you for taking the time to let us know. I've refreshed the GitHub docs to reflect the change.
