### ISSUE TITLE
List of UEFI-enabled instances does not include M6i

### ISSUE THREAD

**Issue by cperciva** [awsdocs/amazon-ec2-user-guide#193]
`doc_source/ami-boot.md` says:

> Intel and AMD instance types that support UEFI, in addition to Legacy BIOS:
> Virtualized: C5, C5a, C5ad, C5d, C5n, D3, D3en, G4, I3en, M5, M5a, M5ad, M5d, M5dn, M5n, M5zn, R5, R5a, R5ad, R5b, R5d, R5dn, R5n, T3, T3a, and z1d

I'm assuming that M6i should be on this list; also any future Ice Lake instance types.

**Comment by mariflax** [comment]
Thank you for your feedback. I am following up with the engineering team, and will let you know what I find out.

Marilyn Flax
AWS Documentation

**Comment by mariflax** [comment]
Hi,

M6i has been added to the list. Thanks again for your feedback.

Kind regards,
Marilyn
