### ISSUE TITLE
Incorrect x2gd bandwidth, throughput, and IOPS

### ISSUE THREAD

**Issue by RobertCElliott** [awsdocs/amazon-ec2-user-guide#195]
In the first table with these column headers:
"Instance size | Maximum bandwidth (Mbps) | Maximum throughput (MB/s, 128 KiB I/O) | Maximum IOPS (16 KiB I/O)"

the numbers for the x2gd instances are in the wrong columns or just wrong.

For example, for x2gd.metal, IOPS should be 152,000 and bandwidth should be 19,000. The third number (80,000) is not the throughput number - that's an IOPS number from other instance types.

**Comment by julieso** [comment]
Thanks for pointing this out. For example, with x2gd.metal, the API shows that max bandwidth should be 19,000, max throughput should be 2,375 (19,000/8), but IOPS is correct as 80,000. The mistake was that we put 19,000 in the throughput column and then multiplied by 8 to get the bandwidth of 152,000. Similar for the other X2gd sizes.

aws ec2 describe-instance-types --filters Name=instance-type,Values=x2gd.metal --query InstanceTypes[*].EbsInfo
[
    {
        "EbsOptimizedSupport": "default",
        "EncryptionSupport": "supported",
        "EbsOptimizedInfo": {
            "BaselineBandwidthInMbps": 19000,
            "BaselineThroughputInMBps": 2375.0,
            "BaselineIops": 80000,
            "MaximumBandwidthInMbps": 19000,
            "MaximumThroughputInMBps": 2375.0,
            "MaximumIops": 80000
        },
        "NvmeSupport": "required"
    }
]
