### ISSUE TITLE
Is documentation accurate regarding EBS encryption?

### ISSUE THREAD

**Issue by Kamerabuilt** [awsdocs/amazon-ec2-user-guide#198]
Source : https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#encryption-by-default

Under the section "Permissions for IAM users", it says: "You must grant IAM users permission to call the following actions in order to use EBS encryption:
kms:CreateGrant
kms:Decrypt
kms:DescribeKey
kms:GenerateDataKeyWithoutPlainText
kms:ReEncrypt" 

However, in the example given below, it did not include the other IAM permissions, namely, Decrypt, DescribeKey, GenerateDataKeyWithoutPlainText, and ReEncrypt (while having the condition **"kms:GrantIsForAWSResource": true** still in place) 

Should not then the example be as follow: 

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "kms:CreateGrant",
                            "kms:Decrypt", 
                            "kms:DescribeKey",
                            "kms:GenerateDataKeyWithoutPlainText",
                            "kms:ReEncrypt" 
            "Resource": [
                "arn:aws:kms:us-east-2:123456789012:key/abcd1234-a123-456d-a12b-a123b4cd56ef"
            ],
            "Condition": {
                "Bool": {
                    "kms:GrantIsForAWSResource": true
                }
            }
        }
    ]
}

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
