### ISSUE TITLE
Please add information or limitation for Cross Region copy

### ISSUE THREAD

**Issue by goru1984** [awsdocs/amazon-ec2-user-guide#199]
Please add information or limitation for Cross Region copy in this page or section. It helps to consider this service for cross region snapshot copy under DR strategy. I was not aware if cross region feature until i saw it in console and then later found a few lines on Console steps page regarding to create Lifecycle Manager policy.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
