### ISSUE TITLE
Windows & Hyper-V specific instructions

### ISSUE THREAD

**Issue by woodvi** [awsdocs/amazon-ec2-user-guide#202]
I have a PR for this.  As I posted to [StackOverflow](https://superuser.com/questions/1048091/can-i-install-ec2-amazon-linux-os-locally-on-virtual-machine/1628473#1628473) the directions at [Run Amazon Linux 2 as a virtual machine on premises ](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-2-virtual-machine.html)
(as of 2021-Feb) had two steps missing from the documentation in the specific case of running Hyper-V under Windows:

1) Step 1 (part 4) discusses writing an ISO with genisoimage (linux) or hdiutil (MacOS).  It stands to reason that one would need a different tool for Windows: I used [AnyBurn][1] GUI or this command for [magiciso][2] 

    > miso.exe seed.iso -l cidata -a seedconfig\\*

2) Step 3 (part 5) talks about changing the Hyper-v settings.  Don't forget to change the boot order in BIOS settings to "Boot from IDE".  It defaults to boot from CD if you skip this step.  It stands to reason that you can't boot off that ISO: there's hardly anything on it!

  [1]: http://www.anyburn.com/download.php
  [2]: http://www.magiciso.com/

**Comment by kishorecms** [comment]
Magic ISO link is non-functional for some reason.

**Comment by woodvi** [comment]
Looks like Magic ISO is defunct.  Try one of these:
https://en.wikipedia.org/wiki/Comparison_of_disc_image_software
according to their entry for Magic ISO, the DNS is currently missing.

**Comment by woodvi** [comment]
I'm closing this ticket.  I'm surprised that it's still open
1. It's against their policy to recommend software without a thorough review
2. They didn't seem concerned with the boot order
I use WSL, and I suppose (but didn't try) that the Linux docs should be fine for writing the seedconfig.
