### ISSUE TITLE
ED25519 key pair creation doesn't default to pem format

### ISSUE THREAD

**Issue by daniel-norris** [awsdocs/amazon-ec2-user-guide#206]
Hi All, 

I wasn't sure whether this was a bug with the console or with the documentation and actually the expected behaviour when creating a new key pair, so decided to raise this as an issue rather than a pull request. Please let me know if this should live elsewhere. 

**Behaviour**
If you attempt to create a new key pair for EC2 (https://eu-west-2.console.aws.amazon.com/ec2/v2/home?region=eu-west-2#CreateKeyPair:) and select the ED25519 algorithm the documentation states that the:

> "If you chose ED25519 in the previous step, the Private key file format options do not appear, and the private key format defaults to pem."`

However, it defaults to _.ppk_. I haven't checked to see whether the same behaviour occurs when you run this in AWS CLI or in PowerShell.

**Expected Behaviour**
When selecting a new ED25519 key pair for the file to default to _.pem_. 

**Docs**
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html?icmpid=docs_ec2_console

Thanks, Dan

**Comment by mcalmari** [comment]
Hi Dan,

Thanks for reaching out! My test shows this private key defaulting as .pem. I'm guessing you must be on a Windows system? We can add a note stating that the format depends on your OS.

![test-ed25519](https://user-images.githubusercontent.com/80292025/147838061-d50db767-1b0a-477f-b40f-0ca7fb578ada.png)

**Comment by daniel-norris** [comment]
Hey @mcalmari,

Yeah, you're right I'm on Windows. I hadn't thought of that but that makes sense. Seems strange that they have removed the option to choose the format for ED25519. In my case, I'm on a Windows machine but I'm creating the key pair for a Linux instance, so it adds an additional step.

I think your suggestion works :)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
