### ISSUE TITLE
install-nvidia-driver.md has a typo

### ISSUE THREAD

**Issue by DaeyangCho** [awsdocs/amazon-ec2-user-guide#209]
Hi all!

In the amazon-ec2-user-guide/doc_source/**install-nvidia-driver.md** file, there is a section, **Install an additional version of CUDA**.
At step #6, I think the **--no-opengl-lib** should be fixed to **--no-opengl-libs**.
We can check the proper spelling of the option here, https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#pre-installation-actions.

If we fix this, we can save other's time.
Thank you in advance!

**Comment by NaincyKumariKnoldus** [comment]
Hey @DaeyangCho I have fixed this and raised a PR. Please review my PR.
Thanks!

**Comment by amjule** [comment]
@DaeyangCho , @NaincyKumariKnoldus Thank you both. Your contributions are much appreciated.
