### ISSUE TITLE
Correction needed under section "Example: Create a volume with tags"

### ISSUE THREAD

**Issue by zackriso** [awsdocs/amazon-ec2-user-guide#237]
The page mentions: "The aws:TagKeys condition key uses the ForAllValues modifier to indicate that only the keys costcenter and stack are allowed in the request (no other tags can be specified). **_If users don't pass these specific tags, or if they don't specify tags at all, the request fails."_** for the following policy: 

```
{
  "Version": "2012-10-17",
  "Statement": [
        {
      "Sid": "AllowCreateTaggedVolumes",
      "Effect": "Allow",
      "Action": "ec2:CreateVolume",
      "Resource": "arn:aws:ec2:us-east-1:account-id:volume/*",
      "Condition": {
        "StringEquals": {
          "aws:RequestTag/costcenter": "115",
          "aws:RequestTag/stack": "prod"
         },
         "ForAllValues:StringEquals": {
             "aws:TagKeys": ["costcenter","stack"]
         }
       }
     },
     {
       "Effect": "Allow",
       "Action": [
         "ec2:CreateTags"
       ],
       "Resource": "arn:aws:ec2:us-east-1:account-id:volume/*",
       "Condition": {
         "StringEquals": {
             "ec2:CreateAction" : "CreateVolume"
        }
      }
    }
  ]
}
```
The sentence "_If users don't pass these specific tags, or if they don't specify tags at all, the request fails." can be misleading, because that hold true for the first condition block: 

```
"StringEquals": {
          "aws:RequestTag/costcenter": "115",
          "aws:RequestTag/stack": "prod"
```

however, for the second block: 

```
 },
         "ForAllValues:StringEquals": {
             "aws:TagKeys": ["costcenter","stack"]
 }
```

if no tags at all are passed during the request, then the condition-operator "ForAllValues" still returns true, as mentioned in here: 

https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_multi-value-conditions.html

"ForAllValues – Use with multivalued condition keys. Tests whether the value of every member of the request set is a subset of the condition key set. The condition returns true if every key value in the request matches at least one value in the policy**. It also returns true if there are no keys in the request, or if the key values resolve to a null data set, such as an empty string. Do not use ForAllValues with an Allow effect because it can be overly permissive."**

Beside the fact that the documentation says not to use ForAllValues with an Allow as it can be overly permissive.

**Comment by meiringa** [comment]
Hello, thank you for providing this feedback.
I've read through the examples here, and I agree that the usage of the `ForAllValues` condition key is not correct.
I also found a few other examples of incorrect usage in the doc. 

I've corrected all of them and I've updated the public documentation: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ExamplePolicies_EC2.html#iam-example-manage-volumes-tags
