### ISSUE TITLE
Elastic IP page regarding IPv6 support is misleading

### ISSUE THREAD

**Issue by bert128** [awsdocs/amazon-ec2-user-guide#242]
The documentation for "Elastic IP" (elastic-ip-addresses-eip.md) states that IPv6 is not supported.
This implies that the IPv6 implementation is somehow inadequate, and is used as an excuse not to implement IPv6.

The documentation should make it clear that the primary use cases for Elastic IP are to work around deficiencies caused by IPv4, and therefore are not applicable to IPv6. IPv6 blocks assigned to an account are already static, and you can already reassign IPv6 addresses within your static block from one instance to another. 

The documentation should explain how equivalent functionality is already inherent in the IPv6 implementation, and therefore does not require a specific workaround.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
