### ISSUE TITLE
Broken link "Compile and deploy a TensorFlow model on Inf1 using Sagemaker Neo."

### ISSUE THREAD

**Issue by aarora79** [awsdocs/amazon-ec2-user-guide#244]
The link for this reference "[Compile and deploy a TensorFlow model on Inf1 using Sagemaker Neo](https://introduction-to-inferentia.workshop.aws/inf1onsage/02sageintro.html)." on https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/accelerated-computing-instances.html is broken.

![image](https://user-images.githubusercontent.com/14024481/183121080-58f704ed-099e-419c-af2c-6e5634ebcfd2.png)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
