### ISSUE TITLE
Missing the DSA Certificate for Dubai in Instance Identity Documents section

### ISSUE THREAD

**Issue by davdunc** [awsdocs/amazon-ec2-user-guide#248]
the AWS DSA public certificate for me-central-1 is not currently published in the Instance Identity Document section. It would help to have that for verifying the instance identity document signature.

**Comment by jmjesse** [comment]
Thank you for bringing this to our attention. I have engaged the team internally to see what this should be.

**Comment by jmjesse** [comment]
Apologies for the delay on updating this issue, but the requested information has been added for each signature for me-central-1 | Middle East (UAE)

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-identity-documents.html
