### ISSUE TITLE
GP2 burst credits usage

### ISSUE THREAD

**Issue by plumdog** [awsdocs/amazon-ec2-user-guide#249]
From https://github.com/awsdocs/amazon-ec2-user-guide/blob/master/doc_source/general-purpose.md#gp2-volume-performance

> When I/O demand is greater than baseline performance, the volume spends I/O credits to burst to the required performance level (up to 3,000 IOPS). While bursting, I/O credits are spent at a rate of 3 I/O credits per GiB of volume size per second.

The "credits are spent at a rate of 3 I/O credits per GiB of volume size per second" is the bit that doesn't seem to chime with the other information given.

---

For example, a gp2 volume of 100GB. Baseline is 300.

Going by "While bursting, I/O credits are spent at a rate of 3 I/O credits per GiB of volume size per second.", I would expect the burst duration to be `= credits balance / (3 * size in GB) = 5,400,000 / 300 = 18000`

Going by the calculation given in the docs, `burst duration = credits balance / (burst IOPS - baseline IOPS)` would give `= 5,400,000 / (3000 - 300) = 2000` which is what the table says.

---

I think the fix is that
> While bursting, I/O credits are spent at a rate of 3 I/O credits per GiB of volume size per second.

should become something like
> While bursting, one I/O credit is used per second for every IOPS used above the baseline.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
