### ISSUE TITLE
amazon-linux-2-virtual-machine-download YAML Errors

### ISSUE THREAD

**Issue by coingraham** [awsdocs/amazon-ec2-user-guide#25]
The YAML that is currently live [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-2-virtual-machine.html#amazon-linux-2-virtual-machine-download) has errors with regard to the write_files portion.  It should look like this:

```yaml
# NOTE: Cloud-init applies network settings on every boot by default. To retain network 
# settings from first boot, uncomment the following ‘write_files’ section:
# write_files:
#   - 
#     path: /etc/cloud/cloud.cfg.d/80_disable_network_after_firstboot.cfg
#     content: |
#         network:
#             config: disabled
```
This worked when uncommented and has the path first which is more clear to me.

Also note that for MAC users:
```
python -c 'import crypt,getpass; print(crypt.crypt(getpass.getpass()))'
```
This command will not generate the right hash.  You have to run something like this:
```
python -c 'from passlib.hash import sha512_crypt; import getpass; print(sha512_crypt.encrypt(getpass.getpass()))'
```

**Comment by meiringa** [comment]
Hello, thank you for highlighting this. I'll take a look and provide feedback here when I have more information.

**Comment by meiringa** [comment]
Hello,

Thanks for this feedback. 

Your suggestion to move the path to the top of the ‘write files’ section is a good one. It definitely makes the code easier to read and understand. I’m going to update the code as you suggested, and you should see those changes reflect soon.

For the hash compatibility issue; the invocation for generating the hash is different across the different operating systems and the different versions of Python. Unfortunately, we’re not able to cover all of the permutations here. I’ll update the docs to reflect that this command needs to be invoked in Amazon Linux 2.

Thanks for reaching out. Please do let me know if you have any other questions around this.
