### ISSUE TITLE
nothing provides fileutils needed by ec2-ami-tools-1.5-7.noarch

### ISSUE THREAD

**Issue by gchelazzi-klab** [awsdocs/amazon-ec2-user-guide#250]
In a fedora:36 container with ruby 3.1.2
```
ruby --version
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
```
I download the package:
`wget https://s3.amazonaws.com/ec2-downloads/ec2-ami-tools.noarch.rpm`

and when running the install command yum install ec2-ami-tools.noarch.rpm I get the error:

```
[root@9778bf440446 /]# yum install ec2-ami-tools.noarch.rpm
Last metadata expiration check: 0:00:57 ago on Mon Oct  3 11:31:46 2022.
Error: 
 Problem: conflicting requests
  - nothing provides fileutils needed by ec2-ami-tools-1.5-7.noarch
(try to add '--skip-broken' to skip uninstallable packages)
```
`yum install fileutils ` returns error:
```
Last metadata expiration check: 0:01:06 ago on Mon Oct  3 11:41:04 2022.
No match for argument: fileutils
Error: Unable to find a match: fileutils
```
the Ruby gem "fileutils" is installed, but that is not relevant, as yum is looking for a linux package "fileutils".
Installing dileutils is not possible because it is now included in coreutils, which is installed, to no benefit to the install of ec2-ami-tools.noarch.rpm -- this is from the year 2003. Is ec2-ami-tools-1.5-7.noarch this old and not updated since?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
