### ISSUE TITLE
Whois lookup using bgpmon does not work. Timeout

### ISSUE THREAD

**Issue by networkprogrammer** [awsdocs/amazon-ec2-user-guide#254]
Performing a whois lookup to validate ROA does not seem to work as the example uses bgpmon.net and that host does not respond.

`whois -h whois.bgpmon.net " --roa 16509X.X.X.X/X"`
`Timeout.`

https://github.com/awsdocs/amazon-ec2-user-guide/blob/d9c261849b4c58d9a10628fc17f3637da0102bcc/doc_source/ec2-byoip.md?plain=1#L612

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
