### ISSUE TITLE
amazon-linux-https not mentioned in any documentation

### ISSUE THREAD

**Issue by redvivi** [awsdocs/amazon-ec2-user-guide#255]
I think this package, installed in all AWS EC2 instances, would be interesting to be described.

By the say, what is this executable about?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
