### ISSUE TITLE
s3: bucket arn for amazon linux 2023 repository

### ISSUE THREAD

**Issue by maciejprzezdziecki** [awsdocs/amazon-ec2-user-guide#267]
Hello what is the arn for amazon linux 2023 repository on docs there is only relation to al1 /al2 

      "Resource": [
        "arn:aws:s3:::amazonlinux.us-east-1.amazonaws.com/*",
        "arn:aws:s3:::amazonlinux-2-repos-us-east-1/*"
      ]

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
