### ISSUE TITLE
Shoud the RunInstance example use ForAllValues/ForAnyValue set operator?

### ISSUE THREAD

**Issue by Timslhsu** [awsdocs/amazon-ec2-user-guide#27]
The sample to restrict launching certain instance types, which used StringEquals to compare multiple instance types.
"Condition": {
         "StringEquals": {
            "ec2:InstanceType": ["t2.micro", "t2.small"]
         }
      }

"Condition": {
         "StringNotEquals": {
            "ec2:InstanceType": ["t2.micro", "t2.small"]
         }
      }

I tested the policy examples, it seems not working unless adding set operators.

**Comment by meiringa** [comment]
Hello, I'll take a look at the policies you mentioned and provide some feedback shortly.

**Comment by meiringa** [comment]
Hello, 

I've tested both of the policies and they operate as described in the User Guide.

Please note that these example policies are designed for requests that are made with the AWS CLI or an AWS SDK. As such, they might not operate as expected when using the console.

For example policies designed for use with the console, see this topic in the User Guide: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-policies-ec2-console.html#ex-launch-wizard

Thanks again for reaching out. Feel free to let me know if you have any other questions about this.
