### ISSUE TITLE
Login Incorrect Issue During First Boot

### ISSUE THREAD

**Issue by cuoituoi1996** [awsdocs/amazon-ec2-user-guide#33]
Hello, 

I am trying to set up an Amazon Linux 2 instance on premise outside of AWS, more specifically through VMWare ESXi virtualization platform. I have completed all three steps according to the amazon-linux-2-virtual-machine.md guide (making meta-data and user-data and seed.iso, download the image and mount seed.iso during the first boot.) However, during the log in, i keep on getting login incorrect while trying to use the credentials defined in user-data. Pretty sure i didnt just make typos. Any help is appreciated, thank you!

**Comment by cuoituoi1996** [comment]
closed because i figured it out. Mounted the .iso file and restarted the VM too quickly leads to this issue.

**Comment by meiringa** [comment]
I'm glad you were able to resolve this issue, and thank you for providing that feedback. I'll add a note to the docs to mention that you should wait a few minutes between mounting the .iso and starting the VM. Regards, Ashley.
