### ISSUE TITLE
Missing info on EC2 FAQ

### ISSUE THREAD

**Issue by jsbonso** [awsdocs/amazon-ec2-user-guide#34]
Hi, 

There seems to be a missing info on the EC2 FAQ. I know that this github repo is for EC2 User Guide so I couldn't do a pull request, so I guess I'll just report here anyway. In the https://aws.amazon.com/ec2/faqs/#spot-instances FAQ, it says:

_Below is an example of a detailed billing report. The two highlighted areas show how the new report will look based on decimal hours._

But there's no example below that paragraph as shown below.

![image](https://user-images.githubusercontent.com/4216253/43670868-67321834-97d4-11e8-8358-75a69cf9b62e.png)

**Comment by meiringa** [comment]
Hello, 

Thank you for pointing this out. I have forwarded the request to the relevant team. It should be resolved soon. 

Thanks again for the feedback.
-Ashley
