### ISSUE TITLE
Help Wanted - Example IAM policies

### ISSUE THREAD

**Issue by julieso** [awsdocs/amazon-ec2-user-guide#40]
We're looking for examples of the IAM policies that you're using to control access to your EC2 resources. 

You can add a comment here or submit a pull request for one of these pages: https://github.com/awsdocs/amazon-ec2-user-guide/blob/master/doc_source/iam-policies-ec2-console.md or https://github.com/awsdocs/amazon-ec2-user-guide/blob/master/doc_source/ExamplePolicies_EC2.md.

**Comment by ialford** [comment]
@julieso Where are you envisioning these examples live? I'd like to contribute, but there are a lot of options on where to add example documentation and was hoping for a little guidance. 

Thanks!

**Comment by julieso** [comment]
Thanks for reaching out! In my original post, I link to two pages that contain examples. You could submit a pull request for either of these pages, or just post an example as a comment on this thread.
