### ISSUE TITLE
[Snapshot Lifecycle Manager] Snapshot attaching the same tags from Volume

### ISSUE THREAD

**Issue by RogerSik** [awsdocs/amazon-ec2-user-guide#41]
Is it possible with the Snapshot Lifecycle Manager to attach the snapshot the same or specific tags like used "Name" in the volumes?

**Comment by mariflax** [comment]
Hi Roger. I'm looking into this, and will let you know what I find out.

**Comment by mariflax** [comment]
Hi Roger,

The information you’re after is on this page: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/snapshot-lifecycle.html

Volume tags are not inherited by the snapshots that Amazon DLM creates. However, you can specify that tags are added to the snapshot when the snapshot is created.
 
In all the example JSON files on this page, you’ll see “TargetTags” and “TagsToAdd”. TargetTags belong to the volume, and identify the volume to create. TagsToAdd are the tags that are added to the snapshot when its created.

I hope this answered your question.

Kind regards,
Marilyn Flax
AWS Documentation

**Comment by RogerSik** [comment]
TargetTags is to determine which volume to backup and TagsToAdd is to add the **same** tag to all snapshots when I right understand.

All volumes in our situation have all the tag "Name" but with different Value and I want that the snapshot inherits the same Name tag from the same volume. So that I can se snapshot-id-XY has the name tag SRV01 nd snapshot-id-YY has the name tag SRV02 (inherited also from Volume).

**Comment by julieso** [comment]
Yes, you are correct, the same tag is added by a single policy. You can create multiple policies, one per tag.

**Comment by julieso** [comment]
Submitted as a feature request.
