### ISSUE TITLE
Documentation missing for 2018-08-17 version of EC2 metadata

### ISSUE THREAD

**Issue by mcfarlandj** [awsdocs/amazon-ec2-user-guide#42]
There is a path called `events/maintenance/` in metadata version 2018-08-17 that isn't documented in the [Instance Metadata Categories section](https://github.com/awsdocs/amazon-ec2-user-guide/blob/master/doc_source/ec2-instance-metadata.md#instance-metadata-categories) of ec2-instance-metadata.md.

**Comment by mariflax** [comment]
Thanks for the feedback. I'm looking into it.

**Comment by mariflax** [comment]
Hi. Thanks again for bringing this to our attention. "events/maintenance/" is reserved for future use. I've updated the doc to reflect this, and the update should be publicly available soon.
