### ISSUE TITLE
EBSVolumeTypes.md needs more updating for new gp2 limits

### ISSUE THREAD

**Issue by pnickerson-cashstar** [awsdocs/amazon-ec2-user-guide#50]
An [announcement](https://aws.amazon.com/about-aws/whats-new/2018/12/amazon-ebs-increases-performance-of-general-purpose-ssd-gp2-volumes/) says that gp2 volumes now have a maximum baseline performance of 16,000 IOPS, but the table under "I/O Credits and Burst Performance" in EBSVolumeTypes.md still says it's 10,000 IOPS.

Also, under "What happens if I empty my I/O credit balance?" it still says "...  or switching to an io1 volume for workloads that require sustained IOPS performance greater than 10,000 IOPS."

**Comment by pnickerson-cashstar** [comment]
Also, I think this statement in the first section may be wrong: "Volumes greater than 170 GiB up to 214 GiB deliver a maximum throughput of 160 MiB/s if burst credits are available." But I'm not sure about that.

**Comment by julieso** [comment]
Thanks. I've just published documentation updates. You'll find these and other related changes.
