### ISSUE TITLE
Instructions for compiling ENA module removed from documentation

### ISSUE THREAD

**Issue by seanlutner** [awsdocs/amazon-ec2-user-guide#51]
It looks like in the initial commit of all the docs to this repo, the documentation on compiling and enabling the ENA module for linux included the actual dkms commands and the dkms.conf required to perform the compilation. (See: https://github.com/awsdocs/amazon-ec2-user-guide/commit/d1a4d6230b6621fa392847d5211d34bfb1228c51#diff-9907c334785b20f7c26dc2cd4fa82265)

However, these instructions were listed under the Ubuntu section and when the docs were updated to remove the details for Ubuntu in favor of the new method for Ubuntu, the details needed for other linux distros such as CentOS were effectively removed.

At present the documentation reads simply:

`Compile and install the ena module on your instance.`

This is difficult because if you're new to the process you're left with no idea of what to do next. 

Please consider restoring these required steps to the documentation for the `Other Linux` distros including the sample dkms.conf file. Also, please consider documenting the proper way to keep up with the version of the module. As written, it's version 1.0.0 and version 2.0.2g is what's out now.

Thanks!

**Comment by lindseyspirit** [comment]
Thank you for your feedback. I am looking into why this content may have been removed and will get back to you. 
Samantha

**Comment by seanlutner** [comment]
Hi Samantha,
As far as I can tell, the docs were updated because of changes to Ubuntu that makes all those steps unnecessary on Ubuntu but they are still required under CentOS 6 & 7. Restoring those instructions will solve the CentOS 7 side. 

I had also opened a case with AWS support regarding a technical aspect of this and have some additional details that are the steps to follow to compile the ENA driver for CentOS 6. These are:

```
sudo su -
yum -y install kernel-headers kernel-devel git gcc
yum -y update
reboot
# after logging in again
sudo su -
yum -y install kernel-devel kernel-headers
git clone https://github.com/amzn/amzn-drivers
sudo mv amzn-drivers /usr/src/amzn-drivers
cd /usr/src/amzn-drivers/kernel/linux/ena
make
echo "#!bin/sh\n/sbin/insmod /usr/src/amzn-drivers/kernel/linux/ena/ena.ko" > /etc/sysconfig/modules/ena.modules 
chmod 755 /etc/sysconfig/modules/ena.modules
```

Thanks!

**Comment by lindseyspirit** [comment]
Thanks, I'm still gathering some background on this issue and will get back to you as soon as I have more information.

**Comment by lindseyspirit** [comment]
Hi Sean,
Thanks for your patience on this issue. After some investigation and research, I have added the Ubuntu dkms steps and noted that the dkms method is for testing and feedback purposes only. Also, it is noted that using dkms voids the support agreement for your subscription and that other configurations listed in the document are acceptable alternatives to run the latest kernel modules.  Changes should appear in the live documentation (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html) in an hour or less.
