### ISSUE TITLE
Dedicated Host restart 

### ISSUE THREAD

**Issue by wolruf** [awsdocs/amazon-ec2-user-guide#53]
Hello,
It'd be worth documenting if AWS would restart (or not) instances running on a dedicated host in case of permanent failure.

**Comment by lindseyspirit** [comment]
Hi, thanks for the feedback!
The table in this section describes what happens in the permanent-failure state:
https://github.com/awsdocs/amazon-ec2-user-guide/blob/master/doc_source/how-dedicated-hosts-work.md#dedicated-hosts-monitoring

**Comment by wolruf** [comment]
I've seen the table but I think we could clarify that AWS doesn't restart instances in case of permanent-failure

**Comment by lindseyspirit** [comment]
Sure, I will go ahead and add to the definition in the table. Thanks!
