### ISSUE TITLE
missing doc - AWS cloud-init changes/limitations

### ISSUE THREAD

**Issue by diablodale** [awsdocs/amazon-ec2-user-guide#55]
The AWS limited version of cloud-init is not documented. My request is to do so, or to insert a link on this page to such documentation if it already exists.

At https://github.com/awsdocs/amazon-ec2-user-guide/blame/8dcc07c085c9903dbb690447fe2d18458f51a0d9/doc_source/user-data.md#L119 is written

> The Amazon Linux version of cloud-init does not support all of the directives that are available in the base package, and some of the directives have been renamed (such as repo_update instead of apt-upgrade).

I could find no AWS documentation which lists what directives are/not supported. No documentation which lists all directives that have been renamed. It is not possible for AWS customers to write this documentation, as we do not know how AWS has changed the canonical cloud-init capabilities. Customers reverse-engineering and trial/error would be exhaustive and error-prone.

Random docs I did find:

* This same page lists that apt-upgrade was renamed to repo_update. **Please note** that very sentence itself is errant. The correct sentence would be "...such as repo_up**grade** instead of apt-upgrade
* https://aws.amazon.com/amazon-linux-2/release-notes/ that Amazon Linux 2 at some point was updated to cloud-init 18.2, but given the prior text it is unclear what that means since cloud-init is not fully implemented - nor is it clear 18.2 is the current limited version.

**Comment by lindseyspirit** [comment]
Hi and thanks for your feedback about the Amazon Linux cloud-init customizations. I am looking into this and will get back to you as soon as possible.

**Comment by lindseyspirit** [comment]
To follow up, I will work with the appropriate folks to get this information added to the Linux user guide.

**Comment by diablodale** [comment]
Hello. I don't see updates to this page for what you describe. Perhaps you closed this issue before the issue is resolved.

The workflow for issues is to have them open, and when successfully resolved, to close them. This is the workflow that enables the originator (me) to validate the issue was successfully resolved, and if not, to reopen the issue to more work.

Without this workflow, issues can not be successfully tracked by originators without exhaustive re-checking/re-reading. And it could be the work is progressive and the originator shouldn't look at intermediate work, only look at the work when it is fully resolved.

Not using such a workflow would be like a person coming to your front door and *not* knocking (the resolved notification). The person in the house (the originator of the issue) doesn't know someone is outside (the issue is resolved). Resulting in both the person in the house and/or the person outside the house missing opportunities or becoming frustrated.

**Comment by lindseyspirit** [comment]
Apologies for closing the issue before the documentation changes are made. The changes may take a couple of weeks to be added to the guide.

**Comment by diablodale** [comment]
No worries. I understand. Thanks for allowing customers to collab. When you are ready, I commit to looking at the updates.

**Comment by lindseyspirit** [comment]
Still working on this.

**Comment by lindseyspirit** [comment]
The statement you referred to about a limited cloud-init from Amazon Linux is probably 6-7 year old and lost relevance 5 years ago when we adopted 0.7.x on AL AMI. I am removing it from our documentation. Apologies for the outdated information and thank you for your vigilance and patience. Changes in the documentation on docs.aws.amazon.com will not be reflected until tomorrow.

**Comment by lindseyspirit** [comment]
Closing this issue. Please let me know if further clarification or assistance is needed and I will reopen.
