### ISSUE TITLE
Security difference between Dedicated Instances and instances on Dedicated Hosts

### ISSUE THREAD

**Issue by vkatsikaros** [awsdocs/amazon-ec2-user-guide#59]
The [current dedicated hosts overview](https://github.com/awsdocs/amazon-ec2-user-guide/blob/423e7e04aa78b0327eb3961b18fc783a30f382d9/doc_source/dedicated-hosts-overview.md) says 
> There are no performance, security, or physical differences between Dedicated Instances and instances on Dedicated Hosts. 

However, The [current instance purchasing options](https://github.com/awsdocs/amazon-ec2-user-guide/blob/423e7e04aa78b0327eb3961b18fc783a30f382d9/doc_source/dedicated-hosts-overview.md) says 
> Dedicated Hosts can help you address compliance requirements and...

So, if there are no security differences between Dedicated Instances and instances on Dedicated Hosts, then Dedicated Instances should also be coverig compliance requirements?

**Comment by julieso** [comment]
Thanks for pointing this out. I am in the process of updating the documentation.

**Comment by julieso** [comment]
Documentation is updated.
