### ISSUE TITLE
BYOIP --cidr-authorization-context Details

### ISSUE THREAD

**Issue by sudoshoe** [awsdocs/amazon-ec2-user-guide#60]
I am currently in the process of trying to provision several /23 blocks to my account via the aws cli. I am running into an issue with --cidr-authorization-context. What do the "message" and "signature" need to look like?

**Comment by mariflax** [comment]
Hi. Take a look in the EC2 User Guide, specifically step 4 in this procedure: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-byoip.html#prepare-for-byoip

I hope the above helps. Let me know if you need further information.

**Comment by julieso** [comment]
I've clarified the documentation. The message is "1|aws|account|cidr|YYYYMMDD|SHA256|RSAPSS", the signature is the signed message. See the HTML page referenced in the previous comment or https://github.com/awsdocs/amazon-ec2-user-guide/blob/master/doc_source/ec2-byoip.md.
