### ISSUE TITLE
Chart for relation between IOPS and Volume Size is incorrect

### ISSUE THREAD

**Issue by harai** [awsdocs/amazon-ec2-user-guide#63]
The second chart under [General Purpose SSD (gp2) Volumes](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html#EBSVolumeTypes_gp2), which shows the relationship between Maximum IOPS and Volume Size, is incorrect.

The orange line must indicate Baseline Performance while the blue one is for Burst IOPS.

Strangely, this issue exists only in the English version of the page.

**Comment by lindseyspirit** [comment]
Thank you, this has been updated.
