### ISSUE TITLE
Instance RAM size 100GB vs 150GB

### ISSUE THREAD

**Issue by wolruf** [awsdocs/amazon-ec2-user-guide#64]
Hello,
On URI:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-interruptions.html
it is stated hibernate would work with:
"The following instances are supported: C3, C4, C5, M4, M5, R3, and R4, with less than 100 GB of memory."
in the non-spot documentation, the following is specified:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Hibernate.html
"The following instance families are supported: C3, C4, C5, M3, M4, M5, R3, R4, and R5, with less than 150 GB of RAM"

Is the difference expected ?

**Comment by mariflax** [comment]
Hi, yes the difference is expected.

There are different limitations for Spot Instance hibernation and On-Demand Instance hibernation, as documented in the pages you have linked to.

Thank you for taking the time to get clarification! Apologies for the delay in responding to you.

Kind regards,
Marilyn Flax
AWS Documentation
