### ISSUE TITLE
Instance Lifecycle

### ISSUE THREAD

**Issue by matiiponchon** [awsdocs/amazon-ec2-user-guide#67]
Hey,
In [AWS Documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-lifecycle.html) and [ec2-instance-lifecycle.md](https://github.com/awsdocs/amazon-ec2-user-guide/blob/master/doc_source/ec2-instance-lifecycle.md), there is an issue in the _Instance Lifecycle_.

I can stop an instance in pending status.
I did it using AWS CLI, AWS SDK and AWS Console.

According to the documentation, I can't do this transition.

Is there an issue in the documentation?
Is there an issue handling instance states?

Kind regards,
Matías Ponchón

**Comment by julieso** [comment]
Thanks for the comment. This is a conceptual diagram that I created and it represents the typical lifecycle. There's nothing in the API documentation that says the running state is required. For simplicity, I am going to leave the diagram as is.
