### ISSUE TITLE
EC2 Instance Connect Requirements

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/amazon-ec2-user-guide#68]
In the Console section, it states that "to connect using the console, the instance must have a public IP address (IPv4 or IPv6).

Is this also a requirement for the other 2 options: CLI or with own key and any SSH Client?

The General Prerequisites also states: We recommend that your instance allows inbound SSH traffic from the recommended IP block published for the service. Use the EC2_INSTANCE_CONNECT filter for the service parameter to get the IP address ranges in the EC2 Instance Connect subset. For more information, see AWS IP Address Ranges in the Amazon Web Services General Reference.  

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-methods.html

**Comment by mariflax** [comment]
Hi. A public IP address is only required if you're connecting via the console. You don't need a public IP address for the other two connection options.

Thanks,
Marilyn Flax
AWS Documentation
