### ISSUE TITLE
Configure IAM permissions for EC2 Instance Connect

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/amazon-ec2-user-guide#74]
Hi, I noticed here in the 2 sample policies, specific resources are specified.  

However, from reading https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonec2instanceconnectservice.html and trying in the policy editor, I get the following message: all resources have been selected for you because this service does not allow you to choose specific resources.

Thus, I believe for both of the sample policies should have the following for the resource block: "Resource": "*"

**Comment by mariflax** [comment]
Thanks @jsoncow. I'll get our technical team to review this and get back to you with their response.

**Comment by julieso** [comment]
Apologies for the delayed response. Mariflax found out that the documentation for Instance Connect is correct. She passed on the request to update the information used by the policy editor and the IAM documentation to reflect the fact that resource-level permissions are supported for SendSSHPublicKey.
