### ISSUE TITLE
The performance description of Provisioned IOPS SSD is incorrect

### ISSUE THREAD

**Issue by zxkane** [awsdocs/amazon-ec2-user-guide#76]
[The doc](https://github.com/awsdocs/amazon-ec2-user-guide/blob/master/doc_source/EBSVolumeTypes.md) says,

> Amazon EBS delivers within 10 percent of the provisioned IOPS performance 99.9 percent of the time over a given year.

Does it mean the PIOPS SSD only gets 10% provisioned IOPS performance in a given year?

Should it be corrected as below,

> Amazon EBS delivers **at least 90 percent** of the provisioned IOPS performance 99.9 percent of the time over a given year.

**Comment by julieso** [comment]
Thanks for pointing this out. I'll update the documentation to match the verbiage on this site: https://aws.amazon.com/ebs/features/#SSD-backed_volumes_.28IOPS-intensive.29. Namely, "... deliver the provisioned performance 99.9% of the time"
