### ISSUE TITLE
Instance Lifecycle Image Missing "Stop-Hibernate"

### ISSUE THREAD

**Issue by kentrad** [awsdocs/amazon-ec2-user-guide#81]
Need to update the image to include the "Stop-Hibernate" option.

![instance_lifecycle](https://user-images.githubusercontent.com/54819813/64133045-caf51980-cda1-11e9-9119-19cca248235a.png)

**Comment by meiringa** [comment]
Hello, thank you for pointing this out. I'll update the docs with the missing action. I'll close this issue once the graphic has been updated.

**Comment by meiringa** [comment]
I've updated the graphic in the docs as you suggested. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-lifecycle.html
Thanks again for that feedback!
