### ISSUE TITLE
Include SSM for Amazon Linux AMI  in `Finding a Linux AMI`

### ISSUE THREAD

**Issue by clifflu** [awsdocs/amazon-ec2-user-guide#88]
[Finding a Linux AMI](https://github.com/awsdocs/amazon-ec2-user-guide/blob/master/doc_source/finding-an-ami.md) describes general approaches on how to find AMI using Amazon Console and AWS CLI. And it's been in top places with similar search terms, even with `Amazon Linux AMI ID`. There's a more convenient way for (some) [latest amzn AMI ID](https://aws.amazon.com/blogs/compute/query-for-the-latest-amazon-linux-ami-ids-using-aws-systems-manager-parameter-store/), which IMHO is the best answer to the search term. 

Would be great if you can mention it in *Finding a Linux AMI*, [Amazon Linux product page](https://aws.amazon.com/amazon-linux-ami/), or both.

**Comment by julieso** [comment]
Thanks for the suggestion. I've updated the docs: https://github.com/awsdocs/amazon-ec2-user-guide/blob/master/doc_source/finding-an-ami.md#finding-an-ami-parameter-store.
