### ISSUE TITLE
EC2 tag enforcement

### ISSUE THREAD

**Issue by AjithKumar-Raj** [awsdocs/amazon-ec2-user-guide#89]
I need to create a policy which will enforce ec2 RunInstance with defined six tag key with any value for my cost explorer visibility.

Any request for RunInstance without these six tags key should not create an instance.

**ForAllValues, ForAnyValue** is not helping here - https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_multi-value-conditions.html because these two are based on request set validation.

**aws:RequestTag/keys** is not helping because it's required values for keys. 

Need help to fix this

**Comment by julieso** [comment]
Did you ever find a solution? I fond examples that test whether a condition key exists. I wonder if this syntax could be extended to multiple aws;RequestTag keys:

https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_Null

https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_example-scps.html#example-require-tag-on-create

**Comment by AjithKumar-Raj** [comment]
Thanks @julieso for your valuable info. It's help me to fix the issue.

**Comment by AjithKumar-Raj** [comment]
Hi @julieso, Can you help me to create a policy which will deny the ec2:RunInstances when 
a) the six expected tags not available in the request 
b) those six tags values are null or empty

**Comment by AjithKumar-Raj** [comment]
Null condition return every time true => [example](https://forums.aws.amazon.com/thread.jspa?messageID=778504)

**Comment by Reneehi** [comment]
Hi, I was working on a similar issue today and ran across a premium support topic that may hold the answer to your question about enforcing tags. https://aws.amazon.com/premiumsupport/knowledge-center/iam-policy-tags-deny/

**Comment by AjithKumar-Raj** [comment]
Thanks @Reneehi .
