### ISSUE TITLE
monitoring-instances-status-check_sched.md

### ISSUE THREAD

**Issue by asloan7** [awsdocs/amazon-ec2-user-guide#9]
monitoring-instances-status-check_sched.md
says "the instance retains its IP address and DNS name"
Does that mean private IP and DNS, public IP and DNS, or both?
I am guessing only the former.

Please explicitly state private, or private and public

**Comment by mariflax** [comment]
Thanks for your feedback. The instance retains both its private and public IP address and DNS name. You can read more here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-lifecycle.html.

I will update the doc according to your suggestion to be explicit. Thank you for your input!
