### ISSUE TITLE
Maintain Multi-Volume Snapshots not explained

### ISSUE THREAD

**Issue by timnee** [awsdocs/amazon-ec2-user-guide#90]
Multi-Volume Snapshots needs a better explanation.  Is this instance type policies?  There is no difference in the steps between [Working with Amazon DLM Using the Console](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/snapshot-lifecycle.html#snapshot-lifecycle-console) and [Working with Amazon DLM to Create and Maintain Multi-Volume Snapshots Using the Console](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/snapshot-lifecycle.html#multivolume-lifecycle).

Can you alse please explain what `VariableTags` are?

**Comment by julieso** [comment]
Hello. The difference is whether you specify a resource type of VOLUME or INSTANCE. With separate procedures that differed only by this one setting, it was difficult to spot the difference. I've updated the markdown and the HTML/PDF with a better explanation and consolidated steps. The variable tags are available if the resource type is INSTANCE. The tag values for these tags (instance-id and timestamp) aren't determined until the tag is applied.
