### ISSUE TITLE
ebs-volume-types not consistent

### ISSUE THREAD

**Issue by hegyre** [awsdocs/amazon-ec2-user-guide#93]
Hello,
File [doc_source/ebs-volume-types.md](https://github.com/awsdocs/amazon-ec2-user-guide/blob/master/doc_source/ebs-volume-types.md) is not consistent with the [AWS online doc](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html) itself.

For example:

  | Solid-State Drives (SSD) --> missing (gp2)| Hard Disk Drives (HDD) --> Should be "Provisioned IOPS SSD (io1)" instead
-- | -- | --
Volume Type | General Purpose SSD (gp2) | Provisioned IOPS SSD (io1)
Dominant Performance Attribute | IOPS | IOPS

In fact the online doc has a 4-column table, but the doc here on github only has a 2-column table with incorrect title for the 2nd column header.

**Comment by mariflax** [comment]
Thanks for taking the time to let us know. The AWS online doc is the correct version. I'll refresh the GitHub version so that it's aligned with the online version. Thanks, Marilyn

**Comment by mariflax** [comment]
Hi again. I've subsequently discovered that column spanning is a limitation in GitHub: https://github.com/adam-p/markdown-here/issues/176. Unfortunately the table you pointed to does not render correctly in Markdown. To see the full table, please view it in the [AWS online doc](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html) or view the Markdown code. Thanks, Marilyn

**Comment by hegyre** [comment]
Hello @mariflax ,
What about using this below (from https://github.com/adam-p/markdown-here/issues/176) :

> Unsatisfying workaround: You can use raw HTML

<table id="w328aac25c29c15c13c11b7" class="awsui-util-container">
                        <tbody><tr>
                           <th></th>
                           <th colspan="2" align="center" style="text-align: center;">Solid-State Drives (SSD)</th>
                           <th colspan="2" align="center" style="text-align: center;">Hard Disk Drives (HDD)</th>
                        </tr>
                        <tr>
                           <td><b>Volume Type</b></td>
                           <td>General Purpose SSD (<code class="code">gp2</code>)
                           </td>
                           <td>Provisioned IOPS SSD (<code class="code">io1</code>)
                           </td>
                           <td>Throughput Optimized HDD (<code class="code">st1</code>)
                           </td>
                           <td>Cold HDD (<code class="code">sc1</code>)
                           </td>
                        </tr>
                        <tr>
                           <td><b>Description</b></td>
                           <td>General purpose SSD volume that balances price and performance for a wide variety
                              of workloads
                           </td>
                           <td>Highest-performance SSD volume for mission-critical low-latency or
                              high-throughput workloads 
                           </td>
                           <td>Low-cost HDD volume designed for frequently accessed, throughput-intensive
                              workloads
                           </td>
                           <td>Lowest cost HDD volume designed for less frequently accessed workloads</td>
                        </tr>
                        <tr>
                           <td><b>Use Cases</b></td>
                           <td>
                              <div class="itemizedlist">
                                 <ul class="itemizedlist" type="disc">
                                    <li class="listitem">
                                       <p>Recommended for most workloads</p>
                                    </li>
                                    <li class="listitem">
                                       <p>System boot volumes</p>
                                    </li>
                                    <li class="listitem">
                                       <p>Virtual desktops</p>
                                    </li>
                                    <li class="listitem">
                                       <p>Low-latency interactive apps</p>
                                    </li>
                                    <li class="listitem">
                                       <p>Development and test environments</p>
                                    </li>
                                 </ul>
                              </div>
                           </td>
                           <td>
                              <div class="itemizedlist">
                                 <ul class="itemizedlist" type="disc">
                                    <li class="listitem">
                                       <p>Critical business applications that require sustained IOPS performance, or
                                          more than 16,000 IOPS or 250 MiB/s of throughput per
                                          volume
                                       </p>
                                    </li>
                                    <li class="listitem">
                                       <p>Large database workloads, such as:</p>
                                       <div class="itemizedlist">
                                          <ul class="itemizedlist" type="disc">
                                             <li class="listitem">
                                                <p>MongoDB</p>
                                             </li>
                                             <li class="listitem">
                                                <p>Cassandra</p>
                                             </li>
                                             <li class="listitem">
                                                <p>Microsoft SQL Server</p>
                                             </li>
                                             <li class="listitem">
                                                <p>MySQL</p>
                                             </li>
                                             <li class="listitem">
                                                <p>PostgreSQL</p>
                                             </li>
                                             <li class="listitem">
                                                <p>Oracle</p>
                                             </li>
                                          </ul>
                                       </div>
                                    </li>
                                 </ul>
                              </div>
                           </td>
                           <td>
                              <div class="itemizedlist">
                                 <ul class="itemizedlist" type="disc">
                                    <li class="listitem">
                                       <p>Streaming workloads requiring consistent, fast throughput at a low
                                          price
                                       </p>
                                    </li>
                                    <li class="listitem">
                                       <p>Big data</p>
                                    </li>
                                    <li class="listitem">
                                       <p>Data warehouses</p>
                                    </li>
                                    <li class="listitem">
                                       <p>Log processing</p>
                                    </li>
                                    <li class="listitem">
                                       <p>Cannot be a boot volume</p>
                                    </li>
                                 </ul>
                              </div>
                           </td>
                           <td>
                              <div class="itemizedlist">
                                 <ul class="itemizedlist" type="disc">
                                    <li class="listitem">
                                       <p>Throughput-oriented storage for large volumes of data that is infrequently
                                          accessed
                                       </p>
                                    </li>
                                    <li class="listitem">
                                       <p>Scenarios where the lowest storage cost is important</p>
                                    </li>
                                    <li class="listitem">
                                       <p>Cannot be a boot volume</p>
                                    </li>
                                 </ul>
                              </div>
                           </td>
                        </tr>
                        <tr>
                           <td><b>API Name</b></td>
                           <td><code class="code">gp2</code></td>
                           <td><code class="code">io1</code></td>
                           <td><code class="code">st1</code></td>
                           <td><code class="code">sc1</code></td>
                        </tr>
                        <tr>
                           <td><b>Volume Size</b></td>
                           <td>1 GiB - 16 TiB </td>
                           <td>4 GiB - 16 TiB </td>
                           <td>500 GiB - 16 TiB</td>
                           <td>500 GiB - 16 TiB </td>
                        </tr>
                        <tr>
                           <td><b>Max IOPS per Volume</b></td>
                           <td>16,000 (16 KiB I/O) *</td>
                           <td>64,000 (16 KiB I/O) †</td>
                           <td>500 (1 MiB I/O)</td>
                           <td>250 (1 MiB I/O)</td>
                        </tr>
                        <tr>
                           <td><b>Max Throughput per Volume</b></td>
                           <td>250 MiB/s *</td>
                           <td>1,000 MiB/s †</td>
                           <td>500 MiB/s</td>
                           <td>250 MiB/s</td>
                        </tr>
                        <tr>
                           <td><b>Max IOPS per Instance</b> ††
                           </td>
                           <td>80,000</td>
                           <td>80,000</td>
                           <td>80,000</td>
                           <td>80,000</td>
                        </tr>
                        <tr>
                           <td><b>Max Throughput per Instance</b> ††
                           </td>
                           <td>2,375 MB/s</td>
                           <td>2,375 MB/s</td>
                           <td>2,375 MB/s</td>
                           <td>2,375 MB/s</td>
                        </tr>
                        <tr>
                           <td><b>Dominant Performance Attribute</b></td>
                           <td>IOPS</td>
                           <td>IOPS</td>
                           <td>MiB/s</td>
                           <td>MiB/s</td>
                        </tr>
                     </tbody></table>

**Comment by mariflax** [comment]
Hi heygre. Thanks for demonstrating that the workaround works. However, our Markdown files are generated automatically, and if I were to apply the raw HTML workaround, it will be overwritten the next time we refresh the GitHub repo.
