### ISSUE TITLE
Further Clarification on Spot Instance Data Feed

### ISSUE THREAD

**Issue by nitrag** [awsdocs/amazon-ec2-user-guide#97]
https://github.com/awsdocs/amazon-ec2-user-guide/blob/master/doc_source/spot-data-feeds.md#data-feed-file-name-and-format

**The "Max" in `MyMaxPrice` is misleading and can misconstrued as (My) Max Bid.**

Example use case is `p2.xlarge` where On-Demand price is $0.90, Spot is ~$.038 and Spot 1-hr Reserved Duration is $0.495. In this scenario, my "Max Bid Price" is equal to the On-Demand by default.

According to a support case response (6762523391)

> The amount 0.495 USD refers to the spot price for that hour and not the max bid price. ... You pay the Spot price that's in effect at the beginning of each instance-hour for your running instance, billed to the nearest second. Further with Spot Instances, you never pay more than the maximum price you specify. If the Spot price exceeds your maximum price ( max bid price which is 0.90 USD) for a given instance or if capacity is no longer available, your instance will automatically be terminated

So, `MyMaxPrice` refers to the calculated rate of the instance within the given hour and has nothing to do with the Max Bid. In fact, the "Max" here really doesn't have any meaning here.

Given an output (where an instance ran 10-15 minutes):
```
Timestamp UsageType Operation InstanceID MyBidID MyMaxPrice MarketPrice Charge Version
2020-01-21 19:09:02 UTC	SpotUsage:p2.xlarge	RunInstances:SV006	i-03b7a317447e38aa8	sir-8fd1kt2k	0.495 USD	0.386 USD	0.088 USD	1
```

$0.495 is the spot instance rate (with a reserved duration of 60 minutes), which is why the price is higher than the $0.386 market price.

Further clarity would be nice, not sure if it is possible to rename the headers:
```
MyMaxPrice MarketPrice Charge
MySpotPrice MarketPrice Charged
```

If that's not possible then:
`MyMaxPrice | The maximum price specified for this Spot Instance request.`
to 
`MyMaxPrice | The calculated hourly rate of the spot instance which you will pay in that given hour (timestamp).`

You might also clarify:
`Charge |The price charged for this instance usage.`
to 
`Charge|The total price charged based on the total instance usage to the nearest second.`

**Comment by schmutze** [comment]
Hi, I wanted to clarify that you are referring to Defined Duration Spot Instances (Spot Blocks) for this feedback?
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-requests.html#fixed-duration-spot-instances

**Comment by nitrag** [comment]
Yessir

**Comment by schmutze** [comment]
Please note the concept of "bidding" has been removed from Spot Instances completely in early 2018 (https://aws.amazon.com/blogs/compute/new-amazon-ec2-spot-pricing/). Therefore the value "MyMaxPrice" is correct and is defined as the maximum amount you are willing to pay per hour for a given Spot Instance. There is no concept of "Max Bid Price."

Beyond this, Defined Duration Spot Instances have different pricing than regular Spot Instances. So as you pointed out, Defined Duration Spot Instances aren't subject to the concept of a "Max Price" since prices don't fluctuate as they do for regular Spot Instances.

Does this help clear things up?

**Comment by nitrag** [comment]
I'm aware there is no concept of bidding. I was just pointing out how the language here is confusing especially when it comes to determining Defined Duration costs. 🤷

**Comment by schmutze** [comment]
I understand and your feedback is very helpful. We'll see what we can do to clarify in both docs and review what can be done in the data feed headers. Thanks for your feedback!
